#!/usr/bin/env bash
# cairn-on-mac-install.sh — RUN THIS ON YOUR MAC, ONCE. It is the ONLY Mac installer.
#
# ══════════════════════════════════════════════════════════════════════════════
# WHAT IT DOES, IN ONE LINE:
#   Makes the Claude Code on your Mac BE Cairn — and keeps it in sync with the server.
#
# Cairn is not a program. It is a Claude Code session that has read your context files.
# The Claude in your VS Code has never read them, so it doesn't know who you are. This
# fixes that by putting the context ON the Mac and pointing every session at it.
#
# THE GAP THIS ACTUALLY CLOSES: the Claude converting your Python to Rust — for a paper
# you are FIRST-AUTHORING, under active review by an IEDB maintainer — has no idea Rust is
# high-stakes for you, or that "unearned fluency is a liability" is your own thesis. It
# just writes the Rust and hands it over. After this, it teaches instead.
#
# THERE IS NO LIVE CONNECTION between the two Cairns. They are not talking to each other.
# They SHARE FILES, synced every 5 minutes. That's the whole mechanism.
#
#   memory      server ──▶ Mac   (so Mac-Cairn knows you)
#   transcripts Mac    ──▶ server (so the nightly journal sees your VS Code work)
#   code        Mac    ──▶ server (optional; so you can ask Cairn about uncommitted
#                                  code FROM YOUR PHONE)
#
# ⚠️ THE ONE-WRITER RULE — everything depends on it:
#   The SERVER owns memory.  Mac-Cairn reads it, never writes it.
#   The MAC owns code.       Server-Cairn reads it, never writes it.
#   Two writers to one memory = silent divergence = memory you can't trust = system dead.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SERVER="${SERVER:-}"
CAIRN_HOME="$HOME/cairn"

# Working trees to push UP, so you can ask Cairn about uncommitted code from your phone.
# Leave empty to skip. Editing this list and re-running is safe — it's idempotent.
PROJECTS=(
  "$HOME/Desktop/PEPMatch2.0"
  # "$HOME/Desktop/LabReach"
  # "$HOME/Desktop/rapacon"
)

echo "═══ Installing Cairn on this Mac ═══"
echo "server: $SERVER"
echo

# ── 1. Passwordless SSH (the background job cannot type a password) ────────────
if [[ ! -f "$HOME/.ssh/id_ed25519" && ! -f "$HOME/.ssh/id_rsa" ]]; then
  echo "No SSH key on this Mac. Creating one..."
  ssh-keygen -t ed25519 -N "" -f "$HOME/.ssh/id_ed25519"
fi
echo "Authorizing this Mac on the server (you may be asked for the server password ONCE)..."
ssh-copy-id -o StrictHostKeyChecking=accept-new "$SERVER" 2>/dev/null || true

if ! ssh -o BatchMode=yes -o ConnectTimeout=8 "$SERVER" true 2>/dev/null; then
  echo "❌ Passwordless SSH isn't working, and a background job can't type a password."
  echo "   Fix with:  ssh-copy-id $SERVER"
  echo "   (If you don't know the server password: Hetzner Console → Rescue →"
  echo "    Reset root password → web Console → 'passwd roman')"
  exit 1
fi
echo "✅ passwordless SSH works"

# ── 2. ONE sync script, all three directions ──────────────────────────────────
mkdir -p "$HOME/.cairn" "$CAIRN_HOME"
{
  echo '#!/usr/bin/env bash'
  echo '# Cairn Mac sync. Generated by cairn-on-mac-install.sh — re-run that to change it.'
  echo 'set -uo pipefail'
  echo "SERVER=\"$SERVER\""
  echo ''
  echo '# Big build junk must never cross the wire. .pepidx index files alone are huge.'
  echo "EX=(--exclude '.git/objects' --exclude node_modules --exclude venv --exclude .venv \\"
  echo "    --exclude target --exclude __pycache__ --exclude '*.pyc' --exclude .DS_Store \\"
  echo "    --exclude '*.pepidx' --exclude '*.pkl' --exclude '*.so' --exclude dist \\"
  echo "    --exclude build --exclude .next --exclude '*.rds' --exclude '*.h5' --exclude '*.bam')"
  echo ''
  echo 'ssh "$SERVER" "mkdir -p ~/mac-transcripts ~/agent/mac-mirror" 2>/dev/null'
  echo ''
  echo '# DOWN: memory. --delete so a file deleted on the server disappears here too,'
  echo '# instead of Mac-Cairn reading a ghost. local-only/ deliberately stays on the server.'
  echo "rsync -az --delete --exclude '.git' --exclude 'local-only' \\"
  echo "  \"\$SERVER:~/agent/my-context/\" \"$CAIRN_HOME/my-context/\" 2>/dev/null"
  echo ''
  echo '# UP: this Mac'"'"'s Claude Code transcripts -> the server'"'"'s nightly journal reads them.'
  echo '[ -d "$HOME/.claude/projects" ] && \'
  echo "  rsync -az --include '*/' --include '*.jsonl' --exclude '*' \\"
  echo '    "$HOME/.claude/projects/" "$SERVER:~/mac-transcripts/" 2>/dev/null'
  echo ''
  echo '# UP: working trees (incl. uncommitted) -> ask Cairn about them from your phone.'
  for P in "${PROJECTS[@]}"; do
    echo "[ -d \"$P\" ] && rsync -az --delete \"\${EX[@]}\" \"$P/\" \"\$SERVER:~/agent/mac-mirror/$(basename "$P")/\" 2>/dev/null"
  done
  echo ''
  echo '# DOWN: the backup tarballs. THIS IS WHAT MAKES THE BACKUP REAL.'
  echo '# local-only/ is gitignored, so git can never save it — it gets tarballed on the'
  echo '# server instead. But a tarball sitting on the same box it backs up is ONE COPY,'
  echo '# not a backup. Pulling it here is the second copy on a second machine: 3-2-1.'
  echo 'mkdir -p "$HOME/cairn/backups"'
  echo 'rsync -az "$SERVER:~/backups/" "$HOME/cairn/backups/" 2>/dev/null'
  echo ''
  echo 'echo "$(date "+%F %T") cairn sync ok"'
} > "$HOME/.cairn/sync.sh"
chmod +x "$HOME/.cairn/sync.sh"

echo "Running first sync (this may take a moment)..."
"$HOME/.cairn/sync.sh"
echo "✅ memory mirrored to $CAIRN_HOME/my-context"

# ── 3. The bit that makes Mac-Claude into Cairn ───────────────────────────────
# ~/.claude/CLAUDE.md loads in EVERY Claude Code session on this Mac — every folder,
# the VS Code extension panel, and the integrated terminal alike. All of them run
# locally on the Mac, so all of them read this file.
mkdir -p "$HOME/.claude"
[[ -f "$HOME/.claude/CLAUDE.md" ]] && \
  cp "$HOME/.claude/CLAUDE.md" "$HOME/.claude/CLAUDE.md.bak.$(date +%Y%m%d-%H%M%S)" && \
  echo "(backed up your existing ~/.claude/CLAUDE.md)"

cat > "$HOME/.claude/CLAUDE.md" <<'MD'
# You are Cairn.

Roman's personal agent — the same agent that runs on his server. Same identity, same
memory, same contract. You are simply running on his Mac, which means you can see his
actual code, including everything he hasn't committed.

## Read this before you do anything

His memory is at `~/cairn/my-context/`. **Read these at the start of every session:**

- `soul.md` — who you are.
- `me.md` — who he is, and the behavior contract. Follow it literally.
- `insights.md` — **what you have learned by watching him.** The important one.
- `goals.md`, `current.md` (term, schedule, deadlines), `tasks.md` (the single to-do list).

Load on demand: `learning.md` (before ANY teaching), `voice.md` (before ANY email draft),
`reference/` (project briefings), `projects-work.md` / `projects-personal.md`.

**If it isn't in those files, you don't know it.** Say "I don't have that context" rather
than inventing.

## ⚠️ ONE-WRITER RULE — do not break this

`~/cairn/my-context/` is a **READ-ONLY MIRROR.** Never write to it, never edit it, never
commit in it. It is overwritten from the server every 5 minutes, so anything you write is
silently destroyed — and two writers make the memory diverge, which makes it untrustworthy,
which kills the system.

**The server owns memory. This Mac owns code.**

If something worth remembering happens — a decision, a lesson, a changed plan — **say so
explicitly, clearly labelled, in your final message.** This transcript is shipped to the
server, and the nightly journal reads it and writes it into the log. The loop closes; it
just closes through the server, on purpose.

## The rule that matters most here

**Rust is HIGH STAKES.** Roman is *learning* it. He writes Python and has Claude convert
the logic to Rust — and he is **first-authoring a paper on that Rust engine**, with an IEDB
maintainer actively reviewing his PRs.

Keep the Python-first workflow; it's sound (Python *is* the spec — PEPMatch's own philosophy
makes the Python oracle the arbiter of correctness). **But never hand him Rust as a black
box.** After a conversion, make him read it back: what does this borrow, why `&[u8]` and not
`Vec<u8>`, where does the DFS recurse, what does `seen` actually dedup? Then quiz him. Five
minutes, not a lecture.

Use **his own mechanism** on him — from LabReach: *"what question will the reviewer ask
back, and can you answer it?"* He built that test and never points it at himself.

**The bar is not "wrote it unaided." It is "can defend every line."** Read `learning.md` and
the PEPMatch invariants before touching that code. Same for R/Seurat and major coursework.
GE courses: efficient help is fine.

## The rest of the contract

- **Structure, not open-endedness.** Ordered, checkable steps. Never a blank canvas —
  propose a concrete first step. He runs on small wins.
- **Check his scope.** He over-commits and underestimates time. Say so.
- **Draft, never send.** Email is draft-only, always.
- **Be direct.** Push back with reasoning when a plan conflicts with a goal. Agreeing with
  him when he's wrong is a failure.
- **Never delete something you don't understand — flag it.**
MD

echo "✅ ~/.claude/CLAUDE.md installed — every Claude Code session on this Mac is now Cairn"

# ── 4. launchd: keep it fresh, survive reboots ────────────────────────────────
PLIST="$HOME/Library/LaunchAgents/dev.cairn.sync.plist"
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>dev.cairn.sync</string>
  <key>ProgramArguments</key><array><string>$HOME/.cairn/sync.sh</string></array>
  <key>StartInterval</key><integer>300</integer>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>$HOME/.cairn/sync.log</string>
  <key>StandardErrorPath</key><string>$HOME/.cairn/sync.log</string>
</dict></plist>
PL
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "✅ launchd installed — syncs every 5 min, starts at login"

cat <<EOF

═══════════════════════════════════════════════════════════════
Done. Open VS Code, run \`claude\` in any project folder, and ask:

    "who am I?"

If it knows about PEPMatch, Salk, and the 2-indel PR — Cairn is home.

  memory mirror : $CAIRN_HOME/my-context   ← READ-ONLY. Never edit.
  backups       : $CAIRN_HOME/backups      ← the 2nd copy. This is what makes it a backup.
  identity      : ~/.claude/CLAUDE.md
  sync log      : tail ~/.cairn/sync.log
  add projects  : edit PROJECTS in this script, re-run it
  uninstall     : launchctl unload $PLIST && rm ~/.claude/CLAUDE.md
═══════════════════════════════════════════════════════════════
EOF
