#!/usr/bin/env bash
# install-permissions.sh — install the versioned policy into the layer that ACTUALLY applies.
#
# THE PROBLEM THIS SOLVES
# .claude/settings.json in a repo only loads when cwd is inside that repo. Nobody runs
# Claude from inside agent-machinery/ — interactive sessions run from ~/agent, headless jobs
# cd to ~/agent/my-context. So the carefully-reviewed 123-line policy sitting in this repo
# governed NOTHING, while the near-empty ~/.claude/settings.json silently denied everything.
# That one mistake caused every automation bug we hit on 2026-07-13/14.
#
# ~/.claude/settings.json is the USER level: it applies at EVERY cwd, always. That is the
# only layer that can be trusted to be in force. So: keep the policy versioned in git (here,
# path-free, public-safe), and RENDER it into the user level with personal paths added.
#
# Idempotent. Re-run after any policy edit. Backs up first.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
SRC="$REPO_DIR/.claude/settings.json"
DEST="$HOME/.claude/settings.json"

[[ -f "$SRC" ]] || { echo "ERROR: $SRC not found" >&2; exit 1; }

if [[ -f "$DEST" ]]; then
  cp "$DEST" "$DEST.bak.$(date +%Y%m%d-%H%M%S)"
  echo "backed up existing → $DEST.bak.*"
fi

WORKSPACE="${WORKSPACE_DIR:-$HOME/agent}"

python3 - "$SRC" "$DEST" "$WORKSPACE" <<'PY'
import json, sys, os

src, dest, ws = sys.argv[1], sys.argv[2], sys.argv[3]
policy = json.load(open(src))
perms  = policy["permissions"]

# Preserve user-level keys that are NOT policy (model, theme, statusline, ...).
existing = {}
if os.path.exists(dest):
    try:
        existing = json.load(open(dest))
    except Exception:
        existing = {}
keep = {k: v for k, v in existing.items() if k not in ("permissions", "$comment")}

# Personal paths — these CANNOT live in the public repo, so they are added here.
perms["allow"] = [
    f"Read({ws}/**)",
    f"Edit({ws}/my-context/**)",
    f"Write({ws}/my-context/**)",
    f"Edit({ws}/agent-machinery/**)",
    f"Write({ws}/agent-machinery/**)",
    f"Read({ws}/codebases/**)",
] + perms["allow"]

perms["deny"] = [
    f"Read({ws}/agent-machinery/.env)",
    f"Edit({ws}/agent-machinery/.env)",
    f"Write({ws}/agent-machinery/.env)",
    f"Read({os.path.expanduser('~')}/.ssh/**)",
] + perms["deny"]

out = dict(keep)
out["$comment"] = (
    "GENERATED by agent-machinery/scripts/install-permissions.sh — DO NOT HAND-EDIT. "
    "Edit agent-machinery/.claude/settings.json (versioned, reviewed) and re-run the "
    "installer. This user-level file is the ONLY layer that applies at every cwd, which "
    "is why the policy has to live here to have any effect at all."
)
out["permissions"] = perms
json.dump(out, open(dest, "w"), indent=2)
print(f"installed → {dest}")
print(f"  allow: {len(perms['allow'])}  ask: {len(perms['ask'])}  deny: {len(perms['deny'])}")
PY

# settings.local.json auto-accumulates a rule on every "always allow" click. On 2026-07-12
# it had silently collected read access to the private deploy keys. By 07-14 it had
# re-accumulated 12 rules — including `git push origin main`, which policy says must ASK.
# It gets reset to empty, every install. If something belongs in policy, it goes in the
# VERSIONED file where a human reviews it — not here, where nobody ever looks again.
for LOCAL in "$REPO_DIR/.claude/settings.local.json" "$HOME/.claude/settings.local.json"; do
  if [[ -f "$LOCAL" ]] && grep -q '"allow": \[[^]]' "$LOCAL" 2>/dev/null; then
    echo "⚠️  $LOCAL had drifted — resetting to empty (see insights.md #9)"
  fi
  [[ -f "$LOCAL" ]] && printf '{\n  "permissions": { "allow": [], "deny": [] }\n}\n' > "$LOCAL"
done

echo
echo "Done. Restart any interactive session for it to take effect."
